services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: bang99/weshareu-frontend:latest
    ports:
      - "30080:80"  # 프론트엔드 접근 포트
    networks:
      - weshareyou-network
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: bang99/weshareu-backend:latest
    ports:
      - "8080:8080"  # 백엔드 접근 포트
    networks:
      - weshareyou-network
    depends_on:
      - mongodb
      - mariadb
      - redis
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/wsu
    - SPRING_DATASOURCE_USERNAME=test
    - SPRING_DATASOURCE_PASSWORD=test
    - SPRING_PROFILES_ACTIVE=private
    restart: always

  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - weshareyou-network
    restart: always

  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: wsu
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - weshareyou-network
    restart: always

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    networks:
      - weshareyou-network
    restart: always

networks:
  weshareyou-network:
    driver: bridge

volumes:
  mongo-data:
  mariadb-data:
