spring:
  application:
    name: ${SPRING_APP_NAME}

  data:
    mongodb:
      host: ${DATABASE_HOST}
      port: ${MONGO_DATABASE_PORT}
      database: ${MONGO_DATABASE_NAME}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 30000


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATABASE_HOST}:${MARIA_DATABASE_PORT}/${MARIA_DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  config:
    import: application_prod.yml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  mail:
    host:
      port:
        username: ${EMAIL_ID}
        password: ${EMAIL_PWD}
        properties:
          mail.smtp.auth: true
          mail.smtp.ssl.enable: true
          mail.smtp.ssl.trust: smtp.naver.com
          mail.smtp.ssl.protocols: TLSv1.2
          mail.debug: true

test:
  project:
    topic: dev-topic

logging:
  level:
    org:
      springframework:
        security=DEBUG:

JWT:
  SECRET_KEY: ${SCRET_KEY}
  JWT_SECRET_DEFAULT_VALUE: ${JWT_SECRET_DEFAULT_VALUE}
  JWT_HEADER: ${JWT_HEADER}