spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wsuchat

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/wsu
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  config:
    import: application_prod.yml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
test:
  project:
    topic: dev-topic

logging:
  level:
    org:
      springframework:
        security=DEBUG:

JWT:
  SECRET_KEY: ${SCRET_KEY}
  JWT_SECRET_DEFAULT_VALUE: ${JWT_SECRET_DEFAULT_VALUE}
  JWT_HEADER: ${JWT_HEADER}