spring:
  application:
    name: ${SPRING_APP_NAME}

  data:
    mongodb:
      host: ${DATABASE_HOST}
      port: ${MONGO_DATABASE_PORT}
      database: ${MONGO_DATABASE_NAME}

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATABASE_HOST}:${MARIA_DATABASE_PORT}/${MARIA_DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE}

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
test:
  project:
    topic: dev-topic

#logging:
#  level:
#    org:
#      springframework:
#        security=DEBUG:

JWT:
  SECRET_KEY: ${SCRET_KEY}
  JWT_SECRET_DEFAULT_VALUE: ${JWT_SECRET_DEFAULT_VALUE}
  JWT_HEADER: ${JWT_HEADER}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}