spring:
  application:
    name: ${SPRING_APP_NAME}

  data:
    mongodb:
      host: ${DATABASE_HOST}
      port: ${MONGO_DATABASE_PORT}
      database: ${MONGO_DATABASE_NAME}

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 30000

  sms:
    api-key: ${API_KEY}
    api-secret: ${API_SECRET}
    provider: ${PROVIDER}
    sender: ${SENDER}


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATABASE_HOST}:${MARIA_DATABASE_PORT}/${MARIA_DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  config:
    import: application_prod.yml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    include: private

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  mail:
    host:
      port:
        username: ${EMAIL_ID}
        password: ${EMAIL_PWD}
        properties:
          mail.smtp.auth: true
          mail.smtp.ssl.enable: true
          mail.smtp.ssl.trust: ${EMAIL_HOST}
          mail.smtp.ssl.protocols: TLSv1.2
          mail.debug: true

server:
  forward-headers-strategy: native

test:
  project:
    topic: dev-topic

#logging:
#  level:
#    org:
#      springframework:
#        security=DEBUG:

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

JWT:
  SECRET_KEY: ${SCRET_KEY}
  JWT_SECRET_DEFAULT_VALUE: ${JWT_SECRET_DEFAULT_VALUE}
  JWT_HEADER: ${JWT_HEADER}