apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weshareu-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # HTTPS 리다이렉트 비활성화
    nginx.ingress.kubernetes.io/rewrite-target: /$2  # / 경로 재작성
spec:
  ingressClassName: nginx  # NGINX Ingress Controller 사용
  rules:
    - host: weshareu.local  # weshareu.local 도메인 사용
      http:
        paths:
          - path: /()(.*)  # 프론트엔드 서비스 경로 매핑
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /api(/|$)(.*)  # 백엔드 API 경로 매핑
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-service
                port:
                  number: 7777
